### ISSUE TITLE
Transcodings - This backend doesn't support absolute paths

### ISSUE THREAD

**Issue by jkevingutierrez** [neon-jungle/wagtailvideos#65]
Trying to add transcodings is throwing the next error:

```
Traceback (most recent call last): File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner self.run() File "/usr/local/lib/python3.9/site-packages/wagtailvideos/models.py", line 253, in run input_file = video.file.path File "/usr/local/lib/python3.9/site-packages/django/db/models/fields/files.py", line 57, in path return self.storage.path(self.name) File "/usr/local/lib/python3.9/site-packages/django/core/files/storage.py", line 116, in path raise NotImplementedError("This backend doesn't support absolute paths.") NotImplementedError: This backend doesn't support absolute paths.
```

**Comment by Timusan** [comment]
Is there any update to this old issue? This bug is still present if you use S3 storages.
